TELEGRAM_TOKEN = "8879034494:AAGKwWd-TykH6c_AuUZJLDFJ5zhIAUHVQ8E"
CHAT_ID = "1339776577"

SYMBOLS = [
    "ETH/USDT",
    "LAB/USDT",
    "BEAT/USDT",
    "DEXE/USDT",
    "PLAY/USDT",
    "ERA/USDT",
    "BSB/USDT",
    "AIA/USDT"
]

TIMEFRAME = "5m"

EMA_FAST = 8
EMA_SLOW = 20
